### ISSUE TITLE
1835: Layout ISR window is weird

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#359] opened 2021-03-21 14:39 UTC
Rails version 2.4.5, 1835, Clemens variant.

The layout of the ISR window is weird. In earlier versions, the available certificates were just listed top to bottom. In this version there is first a list of four certs, then next to it a list of three certs, etc. 
Is this something intended, or did I do something wrong?

**Comment by erik-vos** [comment] 2021-03-21 19:33
The column-wise layout is a novelty to show the 1837 version 1 startpacket as intended per the rules.

Now it turns out that the 1835 start packet definition also defines rows and columns, but in this case no distinction is made for the different variants of handling the initial round. The result is that this layout is also applied to variants where it serves no purpose. This should be fixed.

**Comment by erik-vos** [comment] 2021-03-22 16:15
I have restrictedthe `<multipleColumns/>` setting in the StartPacket definition to the Standard and Snake variants. And I was happy to notice that this suppressed not only the column-wise display but also any row/column-based buy restrictions in the Clemens variant. So all seems well now (I did no further testing than just this aspect).

**Closed** 2021-03-29 16:53 UTC
Labels: question
